FROM mybase

WORKDIR /usr/src

RUN git clone https://github.com/raspberrypi/pico-sdk.git

ENV PICO_SDK_PATH=/usr/src/pico-sdk

#RUN echo '#!/bin/sh' >> /usr/src/compile.sh
#RUN echo 'echo "Starting compiler... $1 " ' >> /usr/src/compile.sh


#RUN chmod +x /usr/src/compile.sh
#RUN chmod +x /usr/src/project/pico-compiler.sh


