FROM mybase

#RUN echo '#!/bin/sh' >> /usr/src/compile.sh
#RUN echo 'echo "Starting compiler... $1 " ' >> /usr/src/compile.sh


#RUN chmod +x /usr/src/compile.sh
#RUN chmod +x /usr/src/project/pico-compiler.sh


