//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToadHallCentralHeating {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ToadHall : global::System.Configuration.ApplicationSettingsBase {
        
        private static ToadHall defaultInstance = ((ToadHall)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ToadHall())));
        
        public static ToadHall Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10:00")]
        public string RebootTime {
            get {
                return ((string)(this["RebootTime"]));
            }
            set {
                this["RebootTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SummerProgram {
            get {
                return ((bool)(this["SummerProgram"]));
            }
            set {
                this["SummerProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:00")]
        public string HotWaterStart {
            get {
                return ((string)(this["HotWaterStart"]));
            }
            set {
                this["HotWaterStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19:00")]
        public string HotWaterEnd {
            get {
                return ((string)(this["HotWaterEnd"]));
            }
            set {
                this["HotWaterEnd"] = value;
            }
        }
    }
}
